name: naurt_android
description: A new Flutter plugin project.
version: 0.0.1
publish_to: 'none'
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  naurt_platfrom_interface:
    path: ../naurt_platfrom_interface/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.naurt.naurt_android
        pluginClass: NaurtAndroidPlugin

 